# vim ~/.config/starship1.toml

format = """\
$username\
$hostname\
$directory\
$git_status\
\n$time\
$character"""

[character]
success_symbol = '[\$](bold yellow)'

[username]
style_user = '#0DFFAE bold'
style_root = 'white bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@](green bold)[$hostname](#00C8FF bold)'
disabled = false

[directory]
style = '#0CE8DD bold'
truncation_length = 0
truncate_to_repo = false

[time]
style = '#0DFFAE bold'
disabled = false
format = '[\[$time\]]($style) '
time_format = '%T'

[gcloud]
disabled = true

[battery]
disabled = true

