# vim ~/.config/starship.toml
# https://starship.rs/config/#git-branch

format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$python\
$nodejs\
$kubernetes\
$ruby\
$terraform\
$container\
$docker_context\
\n$time\
$character"""

[character]
success_symbol = '[\$](bold blue)'

[username]
style_user = '#FF6200 bold'
style_root = 'white bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@](white bold)[$hostname](#F2CEAE bold)'
disabled = false

[directory]
style = '#BFA004 bold'
truncation_length = 0
truncate_to_repo = false

[time]
style = '#FF6200 bold'
disabled = false
format = '[\[$time\]]($style) '
time_format = '%T'

